name = "family-birthday-reminder"
compatibility_date = "2026-04-01"

[[d1_databases]]
binding = "DB"
database_name = "family-birthday-reminder-db"
database_id = "79787406-0968-4db8-9ac6-7c552b38477a"
